lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/var/jwt/private.pem'
    public_key: '%kernel.project_dir%/var/jwt/public.pem'
    pass_phrase: 'qwerty'
    token_ttl: 36000
    encoder:
        signature_algorithm: HS256