# config/packages/security.yaml
security:
    password_hashers:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        api_login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        refresh:
            pattern: ^/api/refresh
            stateless: true
            lazy: true

        register:
            pattern: ^/api/register
            stateless: true
            lazy: true

        reset_password_request:
            pattern: ^/api/reset-password
            stateless: true
            lazy: true

        update_password:
            pattern: ^/api/update-password
            stateless: true
            lazy: true

        api:
            pattern: ^/api
            stateless: true
            provider: fos_userbundle
            jwt: ~

        qwerty:
            pattern: ^/api/qwerty
            stateless: true
            lazy: false

    access_control:
        - { path: ^/api/qwerty, roles: ROLE_ADMIN }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/reset-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/admin/, roles: ROLE_ADMIN }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }