# config/packages/security.yaml
security:
    password_hashers:
        FOS\UserBundle\Model\UserInterface: auto

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        api_login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        refresh:
            pattern: ^/api/refresh
            stateless: true
            lazy: true
        register:
            pattern: ^/api/register
            lazy: true
        reset_password_request:
            pattern: ^/api/reset-password
            lazy: true
        update_password:
            pattern: ^/api/update-password
            lazy: true
        api:
            pattern: ^/api/
            stateless: true
            lazy: false
            jwt: ~

    access_control:
        - { path: ^/api/login, role: PUBLIC_ACCESS }
        - { path: ^/api/register, role: PUBLIC_ACCESS }
        - { path: ^/api/resetting, role: PUBLIC_ACCESS }
        - { path: ^/api/admin/, role: ROLE_ADMIN }